services:
  db:
    container_name: pg_db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: default@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

